### ISSUE TITLE
Implement Auth

### ISSUE THREAD

**Issue by rima1881** [rima1881/Flat-Earthers-Frontend#6]

**Comment by rima1881** [comment]
I wanna do it JWT way. And I would prefer not to use a library if possible

**Comment by rima1881** [comment]
I am gonna do a basic implementation for front

**Comment by genericlearner** [comment]
are you working on the backend for this @bryjen?

**Comment by rima1881** [comment]
I think one of you guys should go to help joyal. he is struggling

**Comment by bryjen** [comment]
yuh

**Comment by bryjen** [comment]
This [commit](https://github.com/rima1881/Flat-Earthers-Backend/commit/c39f5def42a29f77a7907ba52491ddfa8640e654) on the backend side. Upon login, the frontend is given an auth token which should be used in subsequent requests under 'X-Auth-Token' as the header. 

```json
// sample return
{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJzdHJpbmciLCJqdGkiOiIyZmIxYzkyZi1iNmNlLTQyNWEtYmM3ZC02NWJiNWY2YmUxNWIiLCJleHAiOjE3Mjc2NzA0NTZ9.NOTAVALIDTOKEN"
}
```

We'll discuss the specifics about how the token is stored & how long it is valid for (along with other details) down the line.

@rima1881 
@genericlearner

**Comment by bryjen** [comment]
reopen cause i forgot yall gotta do stuff on the front too lmao

**Comment by rima1881** [comment]
we done :)
